use chungdenroishopdb;

/*category*/
insert into category(image,name,url,description) values('unknow.jpg','Tranh Slogan','tranh-slogan','Tạo đông lực, Truyền cảm hứng, Tăng tính sáng tạo');
insert into category(image,name,url,description) values('unknow.jpg','Tranh Phong Cảnh','tranh-phong-canh','Tạo đông lực, Truyền cảm hứng, Tăng tính sáng tạo');
insert into category(image,name,url,description) values('unknow.jpg','Tranh Minimalist','tranh-minimalist','Tạo đông lực, Truyền cảm hứng, Tăng tính sáng tạo');
insert into category(image,name,url,description) values('unknow.jpg','Tranh Scandinavian','tranh-scandinavian','Tạo đông lực, Truyền cảm hứng, Tăng tính sáng tạo');
insert into category(image,name,url,description) values('unknow.jpg','Other','other','Tạo đông lực, Truyền cảm hứng, Tăng tính sáng tạo');

/*product*/

-- product - category 1
INSERT INTO `chungdenroishopdb`.`product` (`image`, `name`, `price`, `category_id`) VALUES ( 'Tranh-Tieng-Viet-143.jpg', 'Tranh Slogan - Đừng làm việc chăm chỉ', '180000', '1');
INSERT INTO `chungdenroishopdb`.`product` ( `image`, `name`, `price`, `category_id`) VALUES ('Tranh-Tieng-Viet-136.jpg', 'Tranh Slogan - Trong khi dừng lại để suy nghĩ...', '180000', '1');
INSERT INTO `chungdenroishopdb`.`product` ( `image`, `name`, `price`, `category_id`) VALUES ( 'Tranh-Dong-Luc-dl0178.jpg', 'Tranh Slogan - Kỷ luật là sức mạnh', '180000', '1');
INSERT INTO `chungdenroishopdb`.`product` ( `image`, `name`, `price`, `category_id`) VALUES ('Tranh-Tieng-Viet-119.jpg', 'Tranh Slogan - Đừng sống với cái tôi quá lớn...', '180000', '1');
INSERT INTO `chungdenroishopdb`.`product` ( `image`, `name`, `price`, `category_id`) VALUES ( 'Tranh-Tieng-Viet-118.jpg', 'Tranh Slogan - Tư vấn đúng, tư vấn chuẩn', '180000', '1');
INSERT INTO `chungdenroishopdb`.`product` ( `image`, `name`, `price`, `category_id`) VALUES ('Tranh-Tieng-Viet-116.jpg', 'Tranh Slogan - An toàn không đắt, nó vô giá', '180000', '1');

-- product detail
insert into product_detail(quantity, size,url,product_id, description) values(200,'40x60cm','dung-lam-viec-cham-chi2',19,'Giới thiệu về Tranh động lực tại Chungdenroi
Tranh động lực hay còn gọi là tranh slogan. Một trong những dòng tranh đang nhận được sự yêu thích nhất hiện nay. Như tên gọi, động lực được cấu mang đến sự tinh tế, hoàn hảo kết hợp với những câu slogan chất lượng tạo nên những bức tranh động lực tuyệt vời nhất!. Một bức tranh động lực chất lượng không chỉ đẹp về mặt hình thức mà còn phải truyền tải tốt những thông điệp nó đem lại về mặt ý nghĩa. Cụ thể, thông điệp mà bức tranh slogan mang đến sẽ tạo được động lực, truyền cảm hứng và tăng tính sáng tạo cho bất cứ ai nhìn thấy nó. Chungdenroi là đơn vị có nhiều năm kinh nghiệm trong lĩnh vực thiết kế, in ấn các sản phẩm tranh động lực, tranh văn phòng, tranh nghệ thuật,…Và với kinh nghiệm của mình cũng như thấu hiểu được tâm lý khách hàng, những sản phẩm Chungdenroi mang đến luôn cam kết 100% về mặt chất lượng cũng như đảm bảo một mức giá tốt nhất cho khách hàng của mình.');

insert into product_detail(quantity, size,url,product_id, description) values(200,'40x60cm','trong-khi-dung-lai-de-suy-nghi2',20,'Giới thiệu về Tranh động lực tại Chungdenroi
Tranh động lực hay còn gọi là tranh slogan. Một trong những dòng tranh đang nhận được sự yêu thích nhất hiện nay. Như tên gọi, động lực được cấu mang đến sự tinh tế, hoàn hảo kết hợp với những câu slogan chất lượng tạo nên những bức tranh động lực tuyệt vời nhất!. Một bức tranh động lực chất lượng không chỉ đẹp về mặt hình thức mà còn phải truyền tải tốt những thông điệp nó đem lại về mặt ý nghĩa. Cụ thể, thông điệp mà bức tranh slogan mang đến sẽ tạo được động lực, truyền cảm hứng và tăng tính sáng tạo cho bất cứ ai nhìn thấy nó. Chungdenroi là đơn vị có nhiều năm kinh nghiệm trong lĩnh vực thiết kế, in ấn các sản phẩm tranh động lực, tranh văn phòng, tranh nghệ thuật,…Và với kinh nghiệm của mình cũng như thấu hiểu được tâm lý khách hàng, những sản phẩm Chungdenroi mang đến luôn cam kết 100% về mặt chất lượng cũng như đảm bảo một mức giá tốt nhất cho khách hàng của mình.');

insert into product_detail(quantity, size,url,product_id, description) values(200,'40x60cm','ky-luat-la-suc-manh2',21,'Giới thiệu về Tranh động lực tại Chungdenroi
Tranh động lực hay còn gọi là tranh slogan. Một trong những dòng tranh đang nhận được sự yêu thích nhất hiện nay. Như tên gọi, động lực được cấu mang đến sự tinh tế, hoàn hảo kết hợp với những câu slogan chất lượng tạo nên những bức tranh động lực tuyệt vời nhất!. Một bức tranh động lực chất lượng không chỉ đẹp về mặt hình thức mà còn phải truyền tải tốt những thông điệp nó đem lại về mặt ý nghĩa. Cụ thể, thông điệp mà bức tranh slogan mang đến sẽ tạo được động lực, truyền cảm hứng và tăng tính sáng tạo cho bất cứ ai nhìn thấy nó. Chungdenroi là đơn vị có nhiều năm kinh nghiệm trong lĩnh vực thiết kế, in ấn các sản phẩm tranh động lực, tranh văn phòng, tranh nghệ thuật,…Và với kinh nghiệm của mình cũng như thấu hiểu được tâm lý khách hàng, những sản phẩm Chungdenroi mang đến luôn cam kết 100% về mặt chất lượng cũng như đảm bảo một mức giá tốt nhất cho khách hàng của mình.');

insert into product_detail(quantity, size,url,product_id, description) values(200,'40x60cm','dung-song-voi-cai-toi-qua-lon2',22,'Giới thiệu về Tranh động lực tại Chungdenroi
Tranh động lực hay còn gọi là tranh slogan. Một trong những dòng tranh đang nhận được sự yêu thích nhất hiện nay. Như tên gọi, động lực được cấu mang đến sự tinh tế, hoàn hảo kết hợp với những câu slogan chất lượng tạo nên những bức tranh động lực tuyệt vời nhất!. Một bức tranh động lực chất lượng không chỉ đẹp về mặt hình thức mà còn phải truyền tải tốt những thông điệp nó đem lại về mặt ý nghĩa. Cụ thể, thông điệp mà bức tranh slogan mang đến sẽ tạo được động lực, truyền cảm hứng và tăng tính sáng tạo cho bất cứ ai nhìn thấy nó. Chungdenroi là đơn vị có nhiều năm kinh nghiệm trong lĩnh vực thiết kế, in ấn các sản phẩm tranh động lực, tranh văn phòng, tranh nghệ thuật,…Và với kinh nghiệm của mình cũng như thấu hiểu được tâm lý khách hàng, những sản phẩm Chungdenroi mang đến luôn cam kết 100% về mặt chất lượng cũng như đảm bảo một mức giá tốt nhất cho khách hàng của mình.');

insert into product_detail(quantity, size,url,product_id, description) values(200,'40x60cm','tu-van-dung-tu-van-chuan2',23,'Giới thiệu về Tranh động lực tại Chungdenroi
Tranh động lực hay còn gọi là tranh slogan. Một trong những dòng tranh đang nhận được sự yêu thích nhất hiện nay. Như tên gọi, động lực được cấu mang đến sự tinh tế, hoàn hảo kết hợp với những câu slogan chất lượng tạo nên những bức tranh động lực tuyệt vời nhất!. Một bức tranh động lực chất lượng không chỉ đẹp về mặt hình thức mà còn phải truyền tải tốt những thông điệp nó đem lại về mặt ý nghĩa. Cụ thể, thông điệp mà bức tranh slogan mang đến sẽ tạo được động lực, truyền cảm hứng và tăng tính sáng tạo cho bất cứ ai nhìn thấy nó. Chungdenroi là đơn vị có nhiều năm kinh nghiệm trong lĩnh vực thiết kế, in ấn các sản phẩm tranh động lực, tranh văn phòng, tranh nghệ thuật,…Và với kinh nghiệm của mình cũng như thấu hiểu được tâm lý khách hàng, những sản phẩm Chungdenroi mang đến luôn cam kết 100% về mặt chất lượng cũng như đảm bảo một mức giá tốt nhất cho khách hàng của mình.');

insert into product_detail(quantity, size,url,product_id, description) values(200,'40x60cm','an-toan-khong-dat-no-vo-gia2',24,'Giới thiệu về Tranh động lực tại Chungdenroi
Tranh động lực hay còn gọi là tranh slogan. Một trong những dòng tranh đang nhận được sự yêu thích nhất hiện nay. Như tên gọi, động lực được cấu mang đến sự tinh tế, hoàn hảo kết hợp với những câu slogan chất lượng tạo nên những bức tranh động lực tuyệt vời nhất!. Một bức tranh động lực chất lượng không chỉ đẹp về mặt hình thức mà còn phải truyền tải tốt những thông điệp nó đem lại về mặt ý nghĩa. Cụ thể, thông điệp mà bức tranh slogan mang đến sẽ tạo được động lực, truyền cảm hứng và tăng tính sáng tạo cho bất cứ ai nhìn thấy nó. Chungdenroi là đơn vị có nhiều năm kinh nghiệm trong lĩnh vực thiết kế, in ấn các sản phẩm tranh động lực, tranh văn phòng, tranh nghệ thuật,…Và với kinh nghiệm của mình cũng như thấu hiểu được tâm lý khách hàng, những sản phẩm Chungdenroi mang đến luôn cam kết 100% về mặt chất lượng cũng như đảm bảo một mức giá tốt nhất cho khách hàng của mình.');

